from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN

def create_presentation(data=None):
    prs = Presentation()
    
    # Default data if none provided
    if not data:
        data = {
            "url": "N/A",
            "trustScore": 0,
            "riskScore": 100,
            "verdict": "UNKNOWN",
            "message": "N/A"
        }

    # --- Slide 1: Title Slide ---
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "SHIELD AI SECURITY BRIEFING"
    subtitle.text = f"Target: {data['url']}\nSecurity Status: {data['verdict']}"

    # --- Slide 2: Analysis Results ---
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = "Analysis Briefing"
    tf = slide.shapes.placeholders[1].text_frame
    tf.text = f"Security Summary for: {data['url']}"
    tf.add_paragraph().text = f"• Trust Score: {data['trustScore']}%"
    tf.add_paragraph().text = f"• Risk Score: {data['riskScore']}%"
    tf.add_paragraph().text = f"• System Verdict: {data['verdict']}"
    tf.add_paragraph().text = f"• Insight: {data['message']}"

    # --- Slide 3: Detailed Insights ---
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = "Key Security Indicators"
    tf = slide.shapes.placeholders[1].text_frame
    tf.text = "Technical verification summary:"
    tf.add_paragraph().text = "• BERT Neural Core: Advanced semantic validation across multi-layered nodes."
    tf.add_paragraph().text = "• DNS & SSL Verification: Structural correctness and encryption analysis."
    tf.add_paragraph().text = "• Domain Authority: Historical registration and identity checking."

    # --- Slide 4: Project Overview ---
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = "About Shield AI"
    tf = slide.shapes.placeholders[1].text_frame
    tf.text = "Shield AI is a state-of-the-art URL analysis platform."
    tf.add_paragraph().text = "• Real-time detection of phishing and malicious URLs."
    tf.add_paragraph().text = "• Dual-engine approach: Machine Learning + Heuristic Analysis."
    tf.add_paragraph().text = "• Ultra-premium user interface for seamless interaction."

    # --- Slide 5: Machine Learning Module ---
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = "AI-Driven Intelligence"
    tf = slide.shapes.placeholders[1].text_frame
    tf.text = "Our Random Forest Classifier analyzes structural URL features:"
    tf.add_paragraph().text = "• Feature Extraction: URL length, domain depth, TLD reputation."
    tf.add_paragraph().text = "• Pattern Recognition: Detecting obfuscation and redirection tricks."
    tf.add_paragraph().text = "• Predictive Scoring: Providing a probability-based trust verdict."

    # --- Slide 6: Thank You ---
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = "SCAN COMPLETE"
    slide.placeholders[1].text = "Security Briefing Generated by Shield AI Engine."

    # Save
    import os
    import time
    
    # Ensure reports directory exists
    reports_dir = os.path.join(os.path.dirname(__file__), 'reports')
    if not os.path.exists(reports_dir):
        os.makedirs(reports_dir)
        
    timestamp = int(time.time())
    file_name = f"Shield_Report_{timestamp}.pptx"
    file_path = os.path.join(reports_dir, file_name)
    
    prs.save(file_path)
    print(f"Presentation saved successfully as {file_name}")
    return file_name

if __name__ == "__main__":
    create_presentation()

if __name__ == "__main__":
    create_presentation()
